### ISSUE TITLE
Incompatible with Python 3.10

### ISSUE THREAD

**Issue by ttimasdf** [uranusjr/packaging-dists#9]
When running Docker image built with `python:3-alpine`, simpleindex run with error `unknown encoding`.

change base image to `python:3.8-alpine` solved the issue.

```
pypi-simpleindex-1  | Traceback (most recent call last):
pypi-simpleindex-1  |   File "/usr/local/bin/simpleindex", line 5, in <module>
pypi-simpleindex-1  |     from simpleindex.__main__ import main
pypi-simpleindex-1  |   File "/usr/local/lib/python3.10/site-packages/simpleindex/__main__.py", line 11, in <module>
pypi-simpleindex-1  |     from . import configs, routes
pypi-simpleindex-1  |   File "/usr/local/lib/python3.10/site-packages/simpleindex/configs.py", line 12, in <module>
pypi-simpleindex-1  |     from .routes import Route
pypi-simpleindex-1  |   File "/usr/local/lib/python3.10/site-packages/simpleindex/routes.py", line 7, in <module>
pypi-simpleindex-1  |     import packaging_dists
pypi-simpleindex-1  |   File "/usr/local/lib/python3.10/site-packages/packaging_dists/__init__.py", line 0
pypi-simpleindex-1  | SyntaxError: unknown encoding: future_annotations
```

**Comment by uranusjr** [comment]
Contributions are welcomed.
